enable-magisk-update = true
parallel-jobs = 1
compression-level = 9
riplib = true
remove-rv-integrations-checks = true
# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[Youtube-Ex-morphed]
enabled = true
build-mode = "apk"
arch = "arm64-v8a" 
patches-source = "wchill/rvx-morphed"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Return YouTube Username'"
