enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Ex]
build-mode = "both"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "rufusin/revanced-patches"
integrations-source = "rufusin/revanced-integrations"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"

[Music-Ex]
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"
patches-source = "rufusin/revanced-patches"
integrations-source = "rufusin/revanced-integrations"
included-patches = "'Permanent shuffle' 'Permanent repeat'"
excluded-patches = "'Custom branding name YouTube Music'"

[Twitter-piko]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"