build:
  java_min_version: 17
  tools_dir: ./tools
  output_dir: ./output
  keys_dir: ./keys
  temp_dir: ./tmp

  keystore:
    validity_days: 10000
    key_algorithm: RSA
    key_size: 4096
    sig_algorithm: SHA256withRSA
    distinguished_name: "CN=Revanced Extended, OU=Ministry of Silly Builds, O=Thunderkex, L=CyberSpace, ST=Somewhere Over The Galaxy, C=XX"

  workers: 4

  download_retries: 3
  download_timeout_secs: 120

  version_cache: ./tmp/version_cache.json
